services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ:-America/Los_Angeles}
    container_name: lisa-node-red
    restart: unless-stopped
    ports:
      - "${NODE_RED_BIND_ADDR:-0.0.0.0}:${NODE_RED_PORT:-1880}:1880"
    volumes:
      - ${DATA_ROOT:-/svr/lisa-edge}/docker/volumes/node-red:/data
